package models

import "time"

// Recommendation represents a resource limit recommendation
// for a single container inside a pod, generated by PodOptix.
// One pod with 3 containers = 3 separate recommendations.
type Recommendation struct {
	ID            string `json:"id"             db:"id"`
	ClusterID     string `json:"cluster_id"     db:"cluster_id"`
	Namespace     string `json:"namespace"      db:"namespace"`      // e.g. "payments"
	PodName       string `json:"pod_name"       db:"pod_name"`       // e.g. "payment-api-7d9f"
	ContainerName string `json:"container_name" db:"container_name"` // e.g. "payment-api"

	// what the team currently has set (before PodOptix)
	CurrentCPULimit string `json:"current_cpu_limit" db:"current_cpu_limit"` // e.g. "1000m"
	CurrentMemLimit string `json:"current_mem_limit" db:"current_mem_limit"` // e.g. "1024Mi"

	// p99 values computed from real Prometheus data
	P99CPU float64 `json:"p99_cpu" db:"p99_cpu"` // e.g. 120.5 millicores
	P99Mem float64 `json:"p99_mem" db:"p99_mem"` // e.g. 180.2 MiB

	// recommended limits = p99 x 2 (the core value PodOptix provides)
	RecommendedCPULimit string `json:"recommended_cpu_limit" db:"recommended_cpu_limit"` // e.g. "241m"
	RecommendedMemLimit string `json:"recommended_mem_limit" db:"recommended_mem_limit"` // e.g. "360Mi"

	Window    string    `json:"window"     db:"window"`     // data window used e.g. "7d"
	CreatedAt time.Time `json:"created_at" db:"created_at"` // when this recommendation was generated
}
