package models

import "time"

// RecommendationStatus represents the current state of a recommendation.
type RecommendationStatus string

const (
	// Recommendation will be available after 7 days of metrics history.
	StatusNewService RecommendationStatus = "new_service"

	// StatusReady means p99 has been computed and recommendation is available.
	StatusReady RecommendationStatus = "ready"
)

// Recommendation represents a resource limit recommendation for a single container inside a pod, generated by PodOptix.
// One pod with 3 containers = 3 separate recommendations.
// All CPU values are stored in millicores (int).   1000m = 1 core
// All Memory values are stored in Mebibytes (int). 1024Mi = 1Gi
type Recommendation struct {
	ID            string `json:"id"             db:"id"`
	ClusterID     string `json:"cluster_id"     db:"cluster_id"`
	Namespace     string `json:"namespace"      db:"namespace"`      // e.g. "payments"
	PodName       string `json:"pod_name"       db:"pod_name"`       // e.g. "payment-api-7d9f"
	ContainerName string `json:"container_name" db:"container_name"` // e.g. "payment-api"

	// status — tells the user if recommendation is ready or still collecting data
	Status RecommendationStatus `json:"status" db:"status"`

	// current limits set by the team — stored in millicores and MiB
	CurrentCPULimit int `json:"current_cpu_limit" db:"current_cpu_limit"` // e.g. 1000 (millicores)
	CurrentMemLimit int `json:"current_mem_limit" db:"current_mem_limit"` // e.g. 1024 (MiB)

	// p99 values computed from real Prometheus data
	// empty if Status is "new_service"
	P99CPU float64 `json:"p99_cpu" db:"p99_cpu"` // e.g. 120.5 millicores
	P99Mem float64 `json:"p99_mem" db:"p99_mem"` // e.g. 180.2 MiB

	// recommended limits = p99 x 2 — stored in millicores and MiB
	// empty if Status is "new_service"
	RecommendedCPULimit int `json:"recommended_cpu_limit" db:"recommended_cpu_limit"` // e.g. 241 (millicores)
	RecommendedMemLimit int `json:"recommended_mem_limit" db:"recommended_mem_limit"` // e.g. 360 (MiB)

	Window    string    `json:"window"     db:"window"`     // data window used e.g. "7d"
	CreatedAt time.Time `json:"created_at" db:"created_at"` // when this recommendation was generated
}
